### ISSUE TITLE
Package isbinaryfile is broken. Cannot run the script. 

### ISSUE THREAD

**Issue by SupaMario123** [mikenorthorp/gulp-shopify-upload#36]
I followed the instructions and came up with the following error:

`MY_NAME@MacBook-Air-von-Mario MY_PROJECT % npm run gulp

> PROJECT-shop@0.0.1 gulp
> gulp

(node:64602) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/MA_NAME/Projects/PROJECT_NAME-shop/node_modules/isbinaryfile/package.json' of './lib/panino.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/MY_NAME/Projects/PROJECT-shop/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/MY_NAME/Projects/PROJECT-shop/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/MY_NAME/Projects/PROJECT-shop/gulpfile.js:17:6)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at requireOrImport (/Users/myName/Projects/PROJECT-shop/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}`

Seems like the package isbinaryfile is broken. Is their any way to fix this? Would be awesome!

I am working an an MacBook Air with M1 chip. And tested yarn and npm to install modules.

**Comment by SupaMario123** [comment]
i recommend everyone to use the shopify cli. it is awesome!
